### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by poc0204**
張郡驛 第三周
http://3.87.217.170:3000/
http://3.87.217.170:3000/attraction/1

### CODE REVIEW

**Comment by cwpeng** [comment]
1. Font size of navigator is too small in all devices.
2. Font size of order box is too small in middle size devices.

Try to use font size specified in design.

未命名-4

**Comment by poc0204** [comment]
張郡驛 第三周 已修改
http://3.87.217.170:3000/
http://3.87.217.170:3000/attraction/1

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by poc0204** [comment]
老師我Merge pull 不能按捏QQ

**Pull request merged**
