### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by poc0204**
第二周作業
張郡驛
http://3.87.217.170:3000/

### CODE REVIEW

**Comment by cwpeng** [comment]
Your layout exceeds screen width in small and middle devices. (screen width <1200px)

**Comment by poc0204** [comment]
第二周作業 已修改
張郡驛
http://3.87.217.170:3000/

**Comment by cwpeng** [comment]
There should be 2 pages in total if I search 北, but your code only show first page of data, never load more pages in keyword search feature.

**Comment by poc0204** [comment]
第二周作業 再次修改
張郡驛
http://3.87.217.170:3000/

**Comment by cwpeng** [comment]
Your server is broken now.

**Comment by poc0204** [comment]
已開
張郡驛
http://3.87.217.170:3000/

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
