### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by poc0204**
張郡驛
第一周作業

### CODE REVIEW

**Comment by poc0204** [comment]
> 張郡驛 第一周作業
http://3.87.217.170:3000/api/attractions?page=0
http://3.87.217.170:3000/api/attractions/1
http://3.87.217.170:3000/api/attractions?page=0&keyword=%E8%97%9D%E8%A1%93

**Comment by cwpeng** [comment]
Response format of http://3.87.217.170:3000/api/attractions?page=0 is incorrect obviously, check API spec carefully, fix it and leave comment for me to review again.

**Comment by poc0204** [comment]
老師改好了

**Comment by cwpeng** [comment]
Incorrect format still. If you cannot get point, feel free to talk/message me to clarify it.

**Comment by poc0204** [comment]
張郡驛 第一周作業已改
http://3.87.217.170:3000/api/attractions?page=0
http://3.87.217.170:3000/api/attractions/1
http://3.87.217.170:3000/api/attractions?page=0&keyword=%E8%97%9D%E8%A1%93

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by poc0204** [comment]
感謝老師~

**Pull request merged**
